### ISSUE TITLE
您好，我准备用你开源的，集成lumen框架，目前无法集成，请问是否能提供；

### ISSUE THREAD

**Issue by JianyuC** [jyiL/aliwaremq#1]
您好，我准备用你开源的，集成lumen框架，目前无法集成，请问是否能提供；

lumen版本:5.8

感谢您的分享；

**Comment by jyiL** [comment]
lumen需要单独加个Provider适配

**Comment by jyiL** [comment]
已支持lumen,版本号1.2.0
